# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file.proto',
  package='file',
  syntax='proto3',
  serialized_pb=_b('\n\nfile.proto\x12\x04\x66ile\"g\n\x07Message\x12\r\n\x05rowID\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x0e\n\x06target\x18\x04 \x01(\x02\x12\x10\n\x08\x44\x65\x61\x64line\x18\x05 \x01(\t\x12\x10\n\x08Released\x18\x06 \x01(\t\x12\x0b\n\x03tag\x18\x07 \x01(\t\"+\n\nPrediction\x12\r\n\x05rowID\x18\x01 \x01(\x05\x12\x0e\n\x06target\x18\x02 \x01(\x02\x32\x41\n\x0c\x44\x61taStreamer\x12\x31\n\x08sendData\x12\x10.file.Prediction\x1a\r.file.Message\"\x00(\x01\x30\x01\x42\x0f\n\x07\x65x.grpc\xa2\x02\x03HSWb\x06proto3')
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='file.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rowID', full_name='file.Message.rowID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='file.Message.date', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='file.Message.target', index=2,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Deadline', full_name='file.Message.Deadline', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Released', full_name='file.Message.Released', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='file.Message.tag', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=123,
)


_PREDICTION = _descriptor.Descriptor(
  name='Prediction',
  full_name='file.Prediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rowID', full_name='file.Prediction.rowID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='file.Prediction.target', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=168,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Prediction'] = _PREDICTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:file.Message)
  ))
_sym_db.RegisterMessage(Message)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTION,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:file.Prediction)
  ))
_sym_db.RegisterMessage(Prediction)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\007ex.grpc\242\002\003HSW'))

_DATASTREAMER = _descriptor.ServiceDescriptor(
  name='DataStreamer',
  full_name='file.DataStreamer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=170,
  serialized_end=235,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendData',
    full_name='file.DataStreamer.sendData',
    index=0,
    containing_service=None,
    input_type=_PREDICTION,
    output_type=_MESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASTREAMER)

DESCRIPTOR.services_by_name['DataStreamer'] = _DATASTREAMER

# @@protoc_insertion_point(module_scope)
