# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file.proto',
  package='file',
  syntax='proto3',
  serialized_pb=_b('\n\nfile.proto\x12\x04\x66ile\"{\n\x07Message\x12\r\n\x05rowID\x18\x01 \x01(\x05\x12\r\n\x05Jours\x18\x02 \x01(\t\x12\x10\n\x08Periodes\x18\x03 \x01(\t\x12\x0f\n\x07Valeurs\x18\x04 \x01(\x05\x12\x10\n\x08\x44\x65\x61\x64line\x18\x05 \x01(\t\x12\x10\n\x08Released\x18\x06 \x01(\t\x12\x0b\n\x03tag\x18\x07 \x01(\t\",\n\nPrediction\x12\r\n\x05rowID\x18\x01 \x01(\x05\x12\x0f\n\x07Valeurs\x18\x02 \x01(\x05\x32\x41\n\x0c\x44\x61taStreamer\x12\x31\n\x08sendData\x12\x10.file.Prediction\x1a\r.file.Message\"\x00(\x01\x30\x01\x42\x0f\n\x07\x65x.grpc\xa2\x02\x03HSWb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='file.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rowID', full_name='file.Message.rowID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Jours', full_name='file.Message.Jours', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Periodes', full_name='file.Message.Periodes', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Valeurs', full_name='file.Message.Valeurs', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Deadline', full_name='file.Message.Deadline', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Released', full_name='file.Message.Released', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='file.Message.tag', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=143,
)


_PREDICTION = _descriptor.Descriptor(
  name='Prediction',
  full_name='file.Prediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rowID', full_name='file.Prediction.rowID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Valeurs', full_name='file.Prediction.Valeurs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=189,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Prediction'] = _PREDICTION

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:file.Message)
  ))
_sym_db.RegisterMessage(Message)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTION,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:file.Prediction)
  ))
_sym_db.RegisterMessage(Prediction)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\007ex.grpc\242\002\003HSW'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class DataStreamerStub(object):
    """The data service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.sendData = channel.stream_stream(
          '/file.DataStreamer/sendData',
          request_serializer=Prediction.SerializeToString,
          response_deserializer=Message.FromString,
          )


  class DataStreamerServicer(object):
    """The data service definition.
    """

    def sendData(self, request_iterator, context):
      """Sends multiple greetings
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_DataStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'sendData': grpc.stream_stream_rpc_method_handler(
            servicer.sendData,
            request_deserializer=Prediction.FromString,
            response_serializer=Message.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'file.DataStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaDataStreamerServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The data service definition.
    """
    def sendData(self, request_iterator, context):
      """Sends multiple greetings
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaDataStreamerStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The data service definition.
    """
    def sendData(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      """Sends multiple greetings
      """
      raise NotImplementedError()


  def beta_create_DataStreamer_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('file.DataStreamer', 'sendData'): Prediction.FromString,
    }
    response_serializers = {
      ('file.DataStreamer', 'sendData'): Message.SerializeToString,
    }
    method_implementations = {
      ('file.DataStreamer', 'sendData'): face_utilities.stream_stream_inline(servicer.sendData),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_DataStreamer_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('file.DataStreamer', 'sendData'): Prediction.SerializeToString,
    }
    response_deserializers = {
      ('file.DataStreamer', 'sendData'): Message.FromString,
    }
    cardinalities = {
      'sendData': cardinality.Cardinality.STREAM_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'file.DataStreamer', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
